name: feathered blue
favicon: null
layout_spectrum: 0.49185
typography_spectrum: 0.74728
title: feathered blue
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#312e29'
    - '#c6a49a'
    - '#63595a'
    - '#d5543e'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
