name: feathered blue
favicon: null
layout_spectrum: 0.49185
typography_spectrum: 0.74728
title: feathered blue
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090a0c'
    - '#fafafa'
    - '#3c303c'
    - '#bfb793'
    - '#707967'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
